# Placeholder for internal Python strict test compatibility macro.
# Placeholder for internal Python strict library compatibility macro.

package(
    default_visibility = ["//tensorflow_lite_support:internal"],
    licenses = ["notice"],  # Apache 2.0
)

py_library(
    name = "tensor_audio",
    srcs = ["tensor_audio.py"],
    deps = [
        # build rule placeholder: numpy dep,
        "//tensorflow_lite_support/python/task/audio/core/pybinds:audio_utils",
    ],
)
