package(
    default_visibility = ["//tensorflow_lite_support:users"],
    licenses = ["notice"],  # Apache 2.0
)

objc_library(
    name = "TFLStringUtil",
    srcs = [
        "sources/TFLStringUtil.mm",
    ],
    hdrs = [
        "sources/TFLStringUtil.h",
    ],
    module_name = "TFLStringUtil",
)
